{
  'inputs':
    [
      {
        'inputFile': './modules/authorization.openapi.json',
        'pathModification': { 'prepend': '/authorization' },
        'description':
          {
            'append': true,
            'title': { 'value': 'Authorization', 'headingLevel': 2 },
          },
      },
      {
        'inputFile': './modules/equipment.openapi.json',
        'pathModification': { 'prepend': '/equipment' },
        'description':
          {
            'append': true,
            'title': { 'value': 'Equipment', 'headingLevel': 2 },
          },
      },
    ],
  'output': './integration.openapi.json',
}
